postgres:
    image: postgres

taigaback:
    image: ipedrazas/taiga-back
    links:
        - postgres:postgres
    ports:
        - ${back_public_port}:8000

taigafront:
    image: ipedrazas/taiga-front
    links:
        - taigaback:taiga-back
    ports:
        - ${front_public_port}:80
    environment:
        - "API_NAME=boot2docker"
